name: PaliBot

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Install dependencies
      run: dotnet restore src/PaliBot.sln

    - name: Build
      run: dotnet build src/PaliBot.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test src/PaliBot.sln --configuration Release --no-build --no-restore /p:CollectCoverage=true /p:CoverletOutput=$GITHUB_WORKSPACE/artifacts/ /p:CoverletOutputFormat=lcov -m:1 --logger trx --results-directory "$GITHUB_WORKSPACE/artifacts/"

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-results
        path: TestResults
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}